image: docker
services:
  - docker:dind
stages:
  - deploy
step-deploy-prod:
  stage: deploy
  script:
    - docker ps
    - docker stop $(docker ps -q)
    - docker build -t sci-map .
    - docker restart -d -p 80:80 --rm --name sci-map sci-map
